version: '3.8'

services:
  backend-php:
    build:
      context: ./backendPhp
      dockerfile: ./docker/php/Dockerfile
    container_name: backend-php
    ports:
      - "9000:9000"
      - "8080:80"

    networks:
      - app-network

  backend-python-compaing:
    build: ./backendPythonCompaing
    container_name: backend-python-compaing
    ports:
      - "8001:8001"
    networks:
      - app-network

  backend-python-upload:
    build: ./backendPythonUpload
    container_name: backend-python-upload
    ports:
      - "8002:8002"
    networks:
      - app-network

  fluir:
    build: ./FrontNext 
    container_name: fluir
    expose:
      - "3000"
    env_file:
      - ./FrontNext/.env
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-fluir
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fluir
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fluir
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-php
      # - backend-python-compaing
      # - backend-python-upload
      - fluir
    networks:
      - app-network

  zookeeper_fluir:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_fluir
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2281:2181"
    networks:
      - app-network

  kafka_fluir:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_fluir
    depends_on:
      - zookeeper_fluir
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_fluir:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_fluir:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka_fluir
    environment:
      KAFKA_BROKERCONNECT: kafka_fluir:9092
    ports:
      - "19000:9000"
    networks:
      - app-network

volumes:
  db-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
