
services:
  backend-php:
    build:
      context: ./backendPhp
      dockerfile: ./docker/php/Dockerfile
    container_name: backend-php
    volumes:
      - ./backendPhp:/var/www
    depends_on:
      - db
      - mongo
    networks:
      - app-network

  backend-python-compaing:
    build: ./backendPythonCompaing
    container_name: backend-python-compaing
    expose:
      - "8001:8000"
    depends_on:
      - mongo
    networks:
      - app-network

  backend-python-upload:
    build: ./backendPythonUpload
    container_name: backend-python-upload
    expose:
      - "8002:8000"
    depends_on:
      - mongo
    networks:
      - app-network

  fluir:
    build: ./FrontNext 
    container_name: fluir
    expose:
      - "3000"
    env_file:
      - ./FrontNext/.env
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fluir
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fluir
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-php
      - backend-python-compaing
      - backend-python-upload
      - fluir
    networks:
      - app-network

volumes:
  db-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
