version: '3.8'

services:
  backend-php:
    build:
      context: ./backendPhp
      dockerfile: ./docker/php/Dockerfile
    container_name: backend-php
    volumes:
      - ./backendPhp:/var/www
    depends_on:
      - db
    networks:
      - app-network

  backend-python-compaing:
    build: ./backendPythonCompaing
    container_name: backend-python-compaing
    expose:
      - "8001:8000"
    networks:
      - app-network

  backend-python-upload:
    build: ./backendPythonUpload
    container_name: backend-python-upload
    expose:
      - "8002:8000"
    networks:
      - app-network

  front-next:
    build: ./FrontNext
    container_name: front-next
    expose:
      - "3000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fluir
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-php
      - backend-python-compaing
      - backend-python-upload
      - front-next
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge